# Generated by Django 5.0.6 on 2024-09-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
